<?xml version="1.0"?>
<package format="3">
  <name>yolo_detector</name>
  <version>0.1.0</version>
  <description>ONNX Runtime inference support for a future YOLO ROS 2 detector component.</description>
  <maintainer email="jacobnzw@gmail.com">Jakub Prüher</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>libopencv-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>